apiVersion: apps/v1
kind: Deployment
metadata:
  name: amun-inspectionbuild-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: amun-inspectionbuild-operator
  template:
    metadata:
      labels:
        name: amun-inspectionbuild-operator
    spec:
      serviceAccountName: amun-inspectionbuild-operator
      containers:
        - name: amun-inspectionbuild-operator
          image: "quay.io/goern/amun-inspectionbuild-operator:v0.1.0"
          imagePullPolicy: "Always"
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "amun-inspectionbuild-operator"
