apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: amun-inspectionbuild-operator
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
      - persistentvolumeclaims
      - events
      - configmaps
      - secrets
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
  - apiGroups:
      - "image.openshift.io"
    resources:
      - "imagestreams"
    verbs:
      - "*"
  - apiGroups:
      - "build.openshift.io"
    resources:
      - "buildconfigs"
      - "builds"
    verbs:
      - "*"
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - "*"
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
    verbs:
      - get
      - create
  - apiGroups:
      - apps
    resourceNames:
      - amun-inspectionbuild-operator
    resources:
      - deployments/finalizers
    verbs:
      - update
  - apiGroups:
      - amun.thoth-station.ninja
    resources:
      - "*"
    verbs:
      - "*"
